### PR TITLE
Finalizing the FBC version 3 specification

### LINKED ISSUE #396: fbc v3: empty lists?
In SBML L3, we generally allow empty lists if the list itself is optional.  This is to allow people to annotate the list itself, even if there are no elements in it.  Another reason is that another package may extend the class of the contained elements, so to the base package, it might look like it has no children at all, as they are all defined in the derived class.

This isn't a hard rule, but it is what I would call a 'goal' of L3 packages.  As such, I would recommend that ListOfUserDefniedConstraints and ListOfKeyValuePairs be allowed to be empty.

(Since ListOfUserDefinedConstraintComponents it itself required, it is reasonable for that to require at least one child.)

### LINKED ISSUE #403: FBC:  No 'reaction2' in final version of FBC v3
libsbml has support for a 'reaction2' attribute of a FluxObjective, but no such attribute exists in the final spec.

@fbergmann @skeating Can you confirm that the attribute wasn't mistakenly left out of the spec?  If not, we should remove 'reaction2' from libsbml.

### LINKED ISSUE #405: fbc-v3: preparing final version
As I think most outstanding issues have been addressed I am now in the process of preparing a final version of the specification document. 

Known issues that will be addressed:
- #396 will be implemented
- red text will be turned black again
- final scan for typos and other inconsistencies
- 

Could I ask that any additional issues or things that I have missed be addressed (or linked) in comments to this issue?

### PR DESCRIPTION
**Pull request by bgoli**
Issues addressed in this PR (addresses #405)
 
- implemented the changes suggested in #396 allowing empty LoUDC and LoKVP
- red text removed for a more soothing reader experience
- fixed an example that was not included properly
- added a, hopefully, final version of the spec as a PDF `sbml-fbc-version-3-release-1.pdf`

### CODE REVIEW

**Review by fbergmann — APPROVED** [review]
@bgoli  thanks for getting this done, there are still some overflows into the margins, that would be great if we could remove them, worst of them are: 

- url: https://github.com/sbmlteam/sbml-specifications/blob/c05d3ad5557727c2139a71080b81d3033a2978b0/sbml-level-3/version-1/fbc/spec/intro.tex#L53
- page 21, line 16 and 25 'http://sbml.org/fbc/keyvaluepair'
- maybe the mailing list link.

**Comment by bgoli** [comment]
Thanks @fbergmann, good points I'll do an overflow check

**Comment by luciansmith** [comment]
Chiming in here so I know when this is merged, and I can email sbml-discuss.

**Comment by luciansmith** [comment]
There are still other things that need to be fixed, but none of us can actually fix them until this merge happens, because we don't have access to Brett's personal github repository.  I'm going ahead and merging this so I can make other fixes and post to sbml-discuss before the JIB deadline.

**Comment by bgoli** [comment]
What is the status of the V3 specification is there anything else that needs to be done?

**Comment by luciansmith** [comment]
I think we're good!  Sorry; I thought this was done for the last JIB issue.  I merged everything into 'develop', and made a few final changes, mostly to the validation rules relating to the final open issues, including one commit I had made to the wrong branch (sorry).  Everything else looks OK, I think.  The JIB directory needs work, I think.

**Pull request merged**
